### ISSUE TITLE
how does this compare to other libs?

### ISSUE THREAD

**Issue by Styxxy** [adamralph/min-ver#19]
Hi,
How does this project compare to [GitTools.GitVersion](https://github.com/GitTools/GitVersion) and [Nerdbank.GitVersion](https://github.com/AArnott/Nerdbank.GitVersioning) ?

**Comment by adamralph** [comment]
@Styxxy thanks for asking.

I evaluated both `GitTools.GitVersion` and `Nerdbank.GitVersion` before starting this, but neither of them works in the way that I want for my projects.

The TL;DR is that `MinVer` is simpler. [_How it works_](https://github.com/adamralph/min-ver#how-it-works) pretty much captures everything. At least, as currently designed, since it's still a work in progress. There is no NuGet package available yet.

> How does this project compare to GitTools.GitVersion ... ?

To some degree, it's a subset of what `GitTools.GitVersion` does. It's much simpler and doesn't do nearly as much. Some of the differences:

- No dependency on a specific branching pattern.
- No inference of version from branch names.
- No inference of version from YAML config.
- No inference of version from commit messages.
- No inference of version from CI build server env vars.
- No creation of metadata code artifacts.
- No automatic fetching of tags, etc. from the repo.
- One package instead of a series of packages.
- No support for `AssemblyInfo.cs`

> How does this project compare to ... Nerdbank.GitVersion?

It's different approach, and again, simpler (some of the differences are already listed under my previous answer for `GitTools.GitVersion`).

Essentially, `Nerdbank.GitVersion` wraps up the injection of the version into the build process from a config file. That means versions are controlled by commits to that config file. `MinVer` works purely on tags. That means it doesn't need some of the types of things that come with `Nerdbank.GitVersion` such as the config file bootstrapper, and it means the version is controlled independently of the commits. E.g. you can tag a commit as a release candidate, build it and deploy. After some time, if the release candidate has no bugs, you can tag _the same commit_ as RTM, build it and deploy.

Also, `Nerdbank.GitVersion` uses the git height for the patch version, and that's not what I want.

**Comment by Styxxy** [comment]
Thanks for the clarification.

Might be interesting to document this ;-) .

**Comment by adamralph** [comment]
@Styxxy yeah, I was thinking the same. 🙂 

I think it's worth getting that into an FAQ when the design is proven, and at least a beta or RC package are available.

Thanks again for raising this.

**Comment by adamralph** [comment]
@Styxxy FYI I raised https://github.com/adamralph/minver/pull/227 based on this conversation. Thanks again for raising this question.
