### ISSUE TITLE
Package authors and owners are set to default values.

### ISSUE THREAD

**Issue by bording** [adamralph/min-ver#43]
The alpha packages have `MinVer.Cli` as the value for the `authors` and `owners` nuspec properties.

Setting the MSBuild `Authors` property controls what the resulting package will have for both `authors` and `owners`.

**Comment by adamralph** [comment]
@bording well spotted, thanks!

The default `authors` and `owners` values are the package ID, and leaving them as the default is intentional, to convey the fact that the package is authored and owned by the community (with me acting as the current steward). You'll see this in other packages I'm looking after such as [Bullseye](https://www.nuget.org/packages/Bullseye/) and [SimpleExec](https://www.nuget.org/packages/SimpleExec/). However, in this case, the package was indeed being built from the `MinVer.Cli` project rather than the `MinVer` project, which caused the anomaly. "MinVer" is the correct value to use, since that is the name of the package. I've fixed this in #46 by switching the packaging to the `MinVer` project.
